# Generated by Django 4.0.2 on 2022-02-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='blockchain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptoapp.blockchain', verbose_name='Sieć'),
        ),
    ]
